### ISSUE TITLE
[ISSUE] Permalink가 글을 침범

### ISSUE THREAD

**Issue by LouiMinister** [chlalstjd430/chlalstjd430.github.io#1]
<img width="1135" alt="스크린샷 2020-05-21 17 58 38" src="https://user-images.githubusercontent.com/33686751/82542442-f23c8280-9b8c-11ea-9d97-9773f46e657f.png">

**Comment by chlalstjd430** [comment]
해당 문제는 저도 인지하고 있는 사항입니다. 추측이지만 기존에 있던 CSS를 수정하면서 겪은 문제인데, 현재 시점에서 해당 부분은 수정하는데 시간이 걸릴듯 하여 방치해준 상태입니다. 정 보기 불편하시면 문제를 해결하는 방법을 구체적으로 제시해주시거나 pr날려주시면 받아주겠습니다~.
